version: "3.8"

services:
  image-service:
    container_name: image-service
    restart: always
    build: ./backend/imageService
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
