version: "3.8"

services:
  # frontend:
  #   container_name: frontend
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - .:/app

  image-service:
    container_name: image-service
    restart: always
    build: ./backend/imageService
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  login-service:
    container_name: login-service
    restart: always
    build: ./backend/loginService
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    links:
      - mongodb
  forum-service:
    container_name: forum-service
    restart: always
    build: ./backend/forumService
    ports:
      - "5004:5004"
    volumes:
      - .:/app
    links:
      - mongodb
  chat-service:
    container_name: chat-service
    restart: always
    build: ./backend/chatService
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    links:
      - mongodb
  post-service:
    container_name: post-service
    restart: always
    build: ./backend/postService
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
